# datasource/jdbc.properties
jdbc.url=jdbc:mysql://39.104.21.117:3307/wintina?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
jdbc.username=root
jdbc.password=wintinadev@0926
jdbc.driver-class-name=com.mysql.cj.jdbc.Driver